Nowy test
dariuszdx/Cypress-first-project pull request #1
Opened 2023-09-04 18:11 UTC by dariuszdx

2023-09-04 18:17 UTC, pbielenda commented on cypress/Pages/components/Magento/basketFormPage.js
> +class basketFormPage {
Niejednolity sposób nazewnictwa klas

2023-09-04 18:23 UTC, pbielenda commented on cypress/Pages/components/Magento/buyingFormPage.js
> +class buyingFormPage {
Niejednolity sposób nazewnictwa klas

2023-09-04 18:23 UTC, pbielenda commented on cypress/Pages/components/Magento/shippingFormPage.js
> +class ShippingFormPage {
Niejednolity sposób nazewnictwa klas

2023-09-04 19:25 UTC, pbielenda requested changes

2023-09-04 19:25 UTC, pbielenda commented on cypress/Pages/components/Magento/basketFormPage.js
> +    get proccedToCheckout() {
Nazwa metody jest jednocześnie opisem tego co dzieje się w środku metody. Przy pisaniu testów istotnym jest zwracanie uwagi na to by łatwo się je czytało. Dlatego też sugeruję do nazwy `proceedToCheckout` dodać `proceedToCheckoutButton` - wtedy łatwiej się odnaleźć który to element na stronie. Ta wskazówka dotyczy również kolejnej metody click :) 

Jest to sugestia, obserwacja z mojej strony - ale bez tego też będzie dobrze działać. Do analizy jak według Ciebie lepiej, do podglądnięcia jak to robią inni.

2023-09-04 19:25 UTC, pbielenda commented on cypress/Pages/components/Magento/basketFormPage.js
> +        return cy.get(".checkout-methods-items > :nth-child(1) > .action > span")
Dosyć skomplikowany selektor mocno narażony na drobne zmiany frontu. Może by to nieco uprościć, np.: `.cart-summary > button`, albo złapać element po tekście buttona?

2023-09-04 19:25 UTC, pbielenda commented on cypress/Pages/components/Magento/basketFormPage.js
> +        this.proccedToCheckout.click();
Czy wiesz jaka jest różnica pomiędzy `proccedTocheckout` od `this.proceedToCheckout`? Używasz `this.proccedToCheckout` -> this powoduje odwołanie do "siebie samego" - tj obiekt na którym działasz wywoła proccedToCheckout na sobie (obiekcie na którym wykonujesz `clickProccedToCheckout`. I to jest ok.

Natomiast metoda która stworzyłeś przyjmuje parametr `proccedToCheckout` - jest on w metodzie nieużywany więc też kompletnie niepotrzbeny.

2023-09-04 19:25 UTC, pbielenda commented on cypress/e2e/E2E-Magento/03_addingFlow.cy.js
> +    it('Should go to basket and change quantity of product', () => {
Uruchomiłem tylko ten 'it' i nie przechodzi - zatem testy są od siebie zależne - do prawidłowego przejścia tego testu wymagane jest by zostały uruchomione poprzednie. Czy to jest zabieg celowy podyktowany istotnymi argumentami? Ogólnie nie jest to zalecana praktyka.

2023-09-04 19:25 UTC, pbielenda commented on cypress/e2e/E2E-Magento/03_addingFlow.cy.js
> +describe('E2E-Correct process of adding a product to the cart', () => {
Testy z tego describe mi padają. Czy masz pewność że są napisane poprawnie?

2023-09-04 19:25 UTC, pbielenda commented on cypress/e2e/E2E-Magento/03_addingFlow.cy.js
> +        cy.wait(10000)
Nie chcemy takich waitów. Czemu ma służyć i jak możemy to napisać lepiej?

2023-09-04 19:25 UTC, pbielenda commented on cypress/Pages/components/Magento/vaiablesMagento.cy.js
> +export const userEmail = 'dariusz12@o2.pl';
W profesjonalnym projekcie byłby problem z takim podejściem. Czy są jakieś przeciwskazania by w ramach testów tworzyć konta i ich używać?

2023-09-04 19:25 UTC, pbielenda commented on cypress/Pages/components/Magento/shippingFormPage.js
> +        return cy.get('.payment-method-content > :nth-child(4) > div.primary > .action > span')
Skomplikowany, potencjalnie problematyczny selektor.

2023-09-04 19:25 UTC, pbielenda commented on cypress/Pages/components/Magento/buyingFormPage.js
> +        return cy.get(':nth-child(4) > .filter-options-title')
Skomplikowany, problematyczny selektor. Mało odporny na drobne modyfikacje frontu.

2023-09-11 10:19 UTC, dariuszdx commented on cypress/Pages/components/Magento/basketFormPage.js
> +        return cy.get(".checkout-methods-items > :nth-child(1) > .action > span")
Przy zmianie selektora , w innych częściach się pojawiają błędy i testy nie przechodzą, np. : "cy.click() can only be called on a single element. Your subject contained 2 elements. Pass { multiple: true } if you want to serially click each element.[L](https://on.cypress.io/click)". Po dodaniu opcji multiple :true też pojawia się błąd.

2023-09-11 10:21 UTC, dariuszdx commented on cypress/Pages/components/Magento/vaiablesMagento.cy.js
> +export const userEmail = 'dariusz12@o2.pl';
Test został podzielony na dwie części więc w ramach testów będzie można używać jednego konta.

2023-09-11 10:44 UTC, dariuszdx commented on cypress/Pages/components/Magento/buyingFormPage.js
> +        return cy.get(':nth-child(4) > .filter-options-title')
Usunięty , nie był potrzebny.

2023-09-12 10:56 UTC, pbielenda commented on cypress/Pages/components/Magento/buyingFormPage.js
> +        return cy.get(':nth-child(4) > .filter-options-title')
Nie widzę commita który to usuwa.

2023-09-16 04:02 UTC, merged